### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "sujalzala66@gmail.com",
  "password": "SHXRWH"
}

### CREATE USER
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "firstName": "Divya",
  "lastName": "Patil",
  "email": "divpatil@gmail.com",
  "contactNumber": "9452876321",
  "joiningDate": "2025-01-15T10:25:30.000Z",
  "password": "divya2930",
  "position": "HR_Executive",
  "department": "HR",
  "status": "Active"
}

### GET ALL USER
GET http://localhost:5000/api/users
Content-Type: application/json

### GET USER BY ID
GET http://localhost:5000/api/users/5
Content-Type: application/json

### UPDATE USER 
PUT http://localhost:5000/api/users/5
Content-Type: application/json

{
  "firstName": "Divyaa",
  "lastName": "Pawar",
  "email": "divyapawar@gmail.com",
  "contactNumber": "7852146398",
  "password": "divya29301"
}

### DELETE USER 
DELETE http://localhost:5000/api/users/5
Content-Type: application/json
