### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin735@gmail.com",
  "password": "admin@123"
}

### USER

### CREATE USER
POST http://localhost:5000/api/users
Content-Type: application/json

{
  "firstName": "Divya",
  "lastName": "Patil",
  "email": "divpatil@gmail.com",
  "contactNumber": "9452876321",
  "joiningDate": "2025-01-15T10:25:30.000Z",
  "password": "divya2930",
  "position": "HR_Executive",
  "department": "HR",
  "status": "Active"
}

### GET ALL USER
GET http://localhost:5000/api/users
Content-Type: application/json

### GET USER BY ID
GET http://localhost:5000/api/users/5
Content-Type: application/json

### UPDATE USER 
PUT http://localhost:5000/api/users/5
Content-Type: application/json

{
  "firstName": "Divyaa",
  "lastName": "Pawar",
  "email": "divyapawar@gmail.com",
  "contactNumber": "7852146398",
  "password": "divya29301"
}

### DELETE USER 
DELETE http://localhost:5000/api/users/5
Content-Type: application/json

### LEAVE TYPE

### CREATE LEAVE TYPE
POST http://localhost:5000/api/leavetype
Content-Type: application/json

{
  "leaveType": "Sick Leave",
  "description": "Leave taken when the employee is unwell or needs medical care."
}

### GET ALL LEAVE TYPE
GET http://localhost:5000/api/leavetype
Content-Type: application/json

### UPDATE LEAVE TYPE 
PUT http://localhost:5000/api/leavetype/
Content-Type: application/json

{
  "leaveType": "Sick Leave",
  "description": "Leave taken when the employee is unwell or needs medical care."
}

### DELETE LEAVE TYPE 
DELETE http://localhost:5000/api/leavetype/
Content-Type: application/json

### LEAVE MANAGEMENT

### APPLY FOR LEAVE (EMPLOYEE)
POST http://localhost:5000/api/leaves
Content-Type: application/json
Authorization: Bearer <USER_TOKEN>
{
  "leaveTypeId": 2,
  "fromDate": "2025-02-01T00:00:00.000Z",
  "toDate": "2025-02-03T00:00:00.000Z",
  "description": "I am suffering from fever."
}

### GET ALL LEAVE (ADMIN)
GET http://localhost:5000/api/leaves
Content-Type: application/json

### UPDATE LEAVE STATUS (ADMIN)
PUT http://localhost:5000/api/leaves/1/status
Content-Type: application/json

{
  "status": "Approved"
}

### PAYROLL

###  PROCESS PAYROLL (ADMIN)
POST http://localhost:5000/api/payroll/process
Content-Type: application/json
Authorization: Bearer <USER_TOKEN>
{
  "employeeId": 2,
  "month": "",
  "basicSalary": "",
  "allowance": "",
  "deduction": "",
  "netSalary": "",
  "payrollStatus": ""
}

### GET ALL PAYROLLS
GET http://localhost:5000/api/payroll
Content-Type: application/json

### GET PAYROLL BY EMPLOYEE
GET http://localhost:5000/api/payroll/5
Content-Type: application/json
